//This file was generated by script swreg2regmap.py

//address macros
`define TIMER_RUN_ADDR 0
`define TIMER_RESET_ADDR 1
`define TIMER_DATA_ADDR 2


//write registers
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 0), TIMER_RUN, wdata[1-1:0])
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 1), TIMER_RESET, wdata[1-1:0])


//read registers
`SIGNAL(rdata_int,`DATA_W)
`SIGNAL2OUT(rdata, rdata_int)

always @* begin
   rdata_int = `DATA_W'd0;
   case(address)
     2: rdata_int = TIMER_DATA | `DATA_W'd0;
     default: rdata_int = `DATA_W'd0;
   endcase
end
