//This file was generated by script swreg2regmap.py


//registers width
`define TIMER_RUN_W 1
`define TIMER_RESET_W 1
`define TIMER_DATA_W DATA_W
//This file was generated by script swreg2regmap.py

//Register Bank Addressing
`define BLANK BLANK
`define BLANK BLANK
`define BLANK BLANK
`define BLANK BLANK
`define BLANK BLANK
`define BLANK BLANK
